const options = {
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      openapi : '3.0.3',
      info: {
        title: 'Baladya API',
        version: '1.0.0',
        description: 'Test Express API with autogenerated swagger doc',
        contact: {
          name: 'dev name',
          email: 'email@gmail.com',
      },
        servers: ['https://localhost:4500']
      },
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/*.js', './models/*.js'],
  };
module.exports = options;